### ISSUE TITLE
Update installation instructions for cloning project in README

### ISSUE THREAD

**Issue by satiewaltz** [satiewaltz/simply-react#1]
The installation instructions need to be updated to utilize the `yarn setup:new` command located in the `package.json`. 

```shell
git clone https://github.com/satiewaltz/simply-react <- needs to be updated to a specific folder
cd simply-react/
... <- Command for removing the `.git` folder 
```

*This issue is intended for people who want to make their first PR to a GitHub project!*

**Comment by Nefari0uss** [comment]
Not quite sure what you want for the change...just have the `README` instructions say to run `yarn setup:new` instead of `yarn start`?

**Comment by satiewaltz** [comment]
Looks great! Closing this issue. 👍
